www:
    dir: '/homer_data/www/html/npdeloss/multi_species_multi-seq_pipeline/'
    url: 'http://homer.ucsd.edu/npdeloss/multi_species_multi-seq_pipeline/'
    source_dirs:
        - 'genomes'
        - 'track_visualizations_bigwigs'
        - 'bigwigs_homer'
targets:
    qc:
        - 'qc_fastqc/index.txt'
    grch38:
        - 'tag_directories/human/grch38/index.txt'
        - 'gene_quantifications_kallisto/human/grch38/gene.tpm.rna.tsv'
        - 'gene_quantifications_kallisto/human/grch38/gene.est_counts.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.raw.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.norm.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.rpkm.rna.tsv'
        - 'bigwigs_homer/human/grch38/index.pos.rna.txt'
        - 'bigwigs_homer/human/grch38/index.neg.rna.txt'
        - 'bigwigs_homer/human/grch38/index.rna.txt'
        - 'bigwigs_homer/human/grch38/index.chip.txt'
        - 'track_visualizations_bigwigs/human/grch38/rna.igv.json'
        - 'track_visualizations_bigwigs/human/grch38/chip.igv.json'
        - 'track_visualizations_bigwigs/human/grch38/rna.igv.html'
        - 'track_visualizations_bigwigs/human/grch38/chip.igv.html'
        - 'tag_directories/human/grch37/index.txt'
    grch37:
        - 'gene_quantifications_kallisto/human/grch37/gene.tpm.rna.tsv'
        - 'gene_quantifications_kallisto/human/grch37/gene.est_counts.rna.tsv'
        - 'gene_quantifications_homer/human/grch37/gene.raw.rna.tsv'
        - 'gene_quantifications_homer/human/grch37/gene.norm.rna.tsv'
        - 'gene_quantifications_homer/human/grch37/gene.rpkm.rna.tsv'
        - 'bigwigs_homer/human/grch37/index.pos.rna.txt'
        - 'bigwigs_homer/human/grch37/index.neg.rna.txt'
        - 'bigwigs_homer/human/grch37/index.rna.txt'
        - 'bigwigs_homer/human/grch37/index.chip.txt'
        - 'track_visualizations_bigwigs/human/grch37/rna.igv.json'
        - 'track_visualizations_bigwigs/human/grch37/chip.igv.json'
        - 'track_visualizations_bigwigs/human/grch37/rna.igv.html'
        - 'track_visualizations_bigwigs/human/grch37/chip.igv.html'
    grcm38:
        - 'tag_directories/mouse/grcm38/index.txt'
        - 'gene_quantifications_kallisto/mouse/grcm38/gene.tpm.rna.tsv'
        - 'gene_quantifications_kallisto/mouse/grcm38/gene.est_counts.rna.tsv'
        - 'gene_quantifications_homer/mouse/grcm38/gene.raw.rna.tsv'
        - 'gene_quantifications_homer/mouse/grcm38/gene.norm.rna.tsv'
        - 'gene_quantifications_homer/mouse/grcm38/gene.rpkm.rna.tsv'
        - 'bigwigs_homer/mouse/grcm38/index.pos.rna.txt'
        - 'bigwigs_homer/mouse/grcm38/index.neg.rna.txt'
        - 'bigwigs_homer/mouse/grcm38/index.rna.txt'
        - 'bigwigs_homer/mouse/grcm38/index.chip.txt'
        - 'track_visualizations_bigwigs/mouse/grcm38/rna.igv.json'
        - 'track_visualizations_bigwigs/mouse/grcm38/chip.igv.json'
        - 'track_visualizations_bigwigs/mouse/grcm38/rna.igv.html'
        - 'track_visualizations_bigwigs/mouse/grcm38/chip.igv.html'
