targets:
    local:
        - 'tag_directories/human/grch38/index.txt'
        - 'gene_quantifications_kallisto/human/grch38/gene.tpm.rna.tsv'
        - 'gene_quantifications_kallisto/human/grch38/gene.est_counts.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.raw.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.norm.rna.tsv'
        - 'gene_quantifications_homer/human/grch38/gene.rpkm.rna.tsv'
        - 'bigwigs_homer/human/grch38/index.pos.rna.txt'
        - 'bigwigs_homer/human/grch38/index.neg.rna.txt'
        - 'bigwigs_homer/human/grch38/index.chip.txt'
        - 'track_visualizations_bigwigs/human/grch38/chip.igv.json'
