preprocessing:
    prefix: 'preprocessing_fastp/'
    fastp:
        prefix: 'preprocessing_fastp/'
        threads: 1
        paired_end:
            adapter_r1: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
            adapter_r2: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
            options: '--cut_by_quality3'
        single_end:
            adapter: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
            options: '--cut_by_quality3'