tag_directories:
    prefix: 'tag_directories/{organism}/{reference}/'
    library_types:
        rna:
            paired_end:
                input_prefix: 'alignment_star/{organism}/{reference}/'
                params:
                    options: '-flip -sspe'
            single_end:
                input_prefix: 'alignment_star/{organism}/{reference}/'
                params:
                    options: ''
        chip:
            paired_end:
                input_prefix: 'alignment_bowtie2/{organism}/{reference}/'
                params:
                    options: '-tbp 1'
            single_end:
                input_prefix: 'alignment_bowtie2/{organism}/{reference}/'
                params:
                    options: '-tbp 1'
        start:
            paired_end:
                input_prefix: 'alignment_bowtie2/{organism}/{reference}/'
                params:
                    options: '-tbp 1'
            single_end:
                input_prefix: 'alignment_bowtie2/{organism}/{reference}/'
                params:
                    options: '-tbp 1'
