wildcard_constraints:
    basename: '[^\/]+'
    organism: '[^\/_]+'
    reference: '[^\/]+'
    library_type: '[^\/_]+'
    cell_type: '[^\/_]+'
    description: '[^\/_]+'
    initials: '[^\/_]+'
    strand: '[A-Za-z0-9]+'
    norm_method: '[A-Za-z0-9_]+'